buildscript {
    repositories {
        maven {
            name = "forge"
            url = "https://mirrors.qlu.edu.cn/bmclapi"
        }
        maven {
            name = "forge-sjtu"
            url = "https://mirror.sjtu.edu.cn/bmclapi"
        }
        maven {
            name = "lss233"
            url = "https://lss233.littleservice.cn/repositories/minecraft"
        }
        maven {
            name = "gitverse"
            url = "https://mvn-mirror.gitverse.ru"
        }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.76', changing: false
    }
}
apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'

version = '1.0'
group = 'com.oleg.steveavenger'
archivesBaseName = 'steveavenger'

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))
minecraft {
    mappings channel: 'official', version: '1.16.5'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                steveavenger {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                steveavenger {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            args '--mod', 'steveavenger', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
            mods {
                steveavenger {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        name = "forge"
        url = "https://mirrors.qlu.edu.cn/bmclapi"
    }
    maven {
        name = "forge-sjtu"
        url = "https://mirror.sjtu.edu.cn/bmclapi"
    }
    maven {
        name = "lss233"
        url = "https://lss233.littleservice.cn/repositories/minecraft"
    }
    maven {
        name = "gitverse"
        url = "https://mvn-mirror.gitverse.ru"
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.16.5-36.2.39'
}

jar {
    manifest {
        attributes([
            "Specification-Title": "steveavenger",
            "Specification-Vendor": "oleg",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"oleg",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}