modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="steveavenger"
version="1.0.0"
displayName="Steve Avenger"
description="Adds a Steve-like mob that fears full leather armor."
authors="Oleg"

[[dependencies.steveavenger]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.steveavenger]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"